jupyterhub:
    hub:
        imagePullSecret:
            username: ENC[AES256_GCM,data:87m+YdXV9xj/b4dgNvBlVYwJI9GVEyYSfM9vOoY=,iv:siLnctpF6x+c/5qYFfATqbHPdKOqt5Cr4wCUBT1T71c=,tag:qPh7svpuMFWYUdW3YfC4fA==,type:str]
            password: ENC[AES256_GCM,data:WPzzKbWuOrVMUzuJQ42pzKIH4/2/iADixCNsVKRc168=,iv:1cwh8WK0KHXX1S85ocH+Nurh+3vJIVSKhY54jkKicYw=,tag:2ZYXiDZF1QaC85jJafWfxQ==,type:str]
    singleuser:
        imagePullSecret:
            username: ENC[AES256_GCM,data:ydl8nOHPyrV/VBl4ko5CI9fJBhrNEKR7ARxCko8=,iv:PZdzihkpNQnJteIwianObXSsUVBi638D7x6PzM6vAos=,tag:VpsL9yEkMiMwi4QdmYQWmA==,type:str]
            password: ENC[AES256_GCM,data:1ZbQvU3SEnHZ3crJxjD8pYn9N988FKC+MjnclLPrf0A=,iv:xO8TULcrT/ZBnSgvjlF+lHWfGIKI+HwyJg4FVQd6rD0=,tag:RmeLrfPq3aRd9nP5jnLgDA==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:SEdp0GP18Jf8/QNgDjaPV53qH4Jm9h8nsvNnmzXl+Qt8/tSk6eEhme11k2wNDXAD5XbisiyXjllGGXpAYNNypw==,iv:XMjirhvs3Z0JxYYxJNybDo/Gz1V855jKnHq1i+t2B8c=,tag:jOam9ZpN4+vAGxJKR3Cqeg==,type:str]
    auth:
        state:
            cryptoKey: ENC[AES256_GCM,data:t7DhpGcxKI2J/LVdc8DavlVUNyJaWfGuGYB24wcOK8kj2jZlc3LOJ9+6cs08Fa3KsOgUtm28szBe3qhOlFLkMw==,iv:YrEdLaKDH0zgw4dQgcWke6AOadj2sqSHoE9tDLmHLMs=,tag:SZtaJYevKGHPGhn3p+KFxw==,type:str]
        cilogon:
            clientId: ENC[AES256_GCM,data:h57VJ6F2DI1lkXzhyqeEBLFdZ29oh9JOtcrSuz4UJOV/D5POqq9j+7Yx0Iagh8FHgE8=,iv:TS+WI2Xtu11lbV/ZB7CWMuRkadJ8s6nfcWJck+tIvEs=,tag:90YqJxCf1i++zcShiabgsQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:PldaZx94kWAcH1N9j6Kh0wHbQ+LGiO4QdIjGIlzkGu4+8UAPuqzo3suGToYz1hdWQsuMb6X/IkFMFbWsr4wJM/CYO62JfeYgNEKpfUAnlhgPTW9kwpE=,iv:/ZaUrNTNqFlRhZ89tbtLel09vTKAK23XQPE5rj6NtUY=,tag:izD+AE0lRmr9ThfWypYUDA==,type:str]
        azuread:
            clientId: ENC[AES256_GCM,data:+i3/2/+0GIYpo5g7LdGPasKVjSNbey+cSDOPAx2DZeLfk6ug,iv:IOwaxDHMLEli2I9CTH+bd3l1uLYNa4Ya008Tz+AsdeM=,tag:Nr+iTl/0jfZSSjbsFwb0Aw==,type:str]
            clientSecret: ENC[AES256_GCM,data:18enNQdDMwgZ0sYmiJXVUzMEt6O3+6aZ/TiVmLdinSdeww==,iv:IAOv8td7eAO/RRxmAUGYL1xPXY88o1ll5jxzmbD32Gk=,tag:TRzVxAcyeFDEocLHkPoM0A==,type:str]
            tenantId: ENC[AES256_GCM,data:0KI7RrC9BIpUe0XPlhPnW2TG6D4tVSFgnFsKtsWaLhavXhRI,iv:LpfEWEdakSrCKGs9il0DmWQK+Z9SU9cZNH1CmMLTRP0=,tag:UkU+PG8+t8rNOKSZuFutuQ==,type:str]
            callbackUrl: ENC[AES256_GCM,data:HpJZxW8Os4Dt0UJflCDh37IIiAbuIewaEF5WXRPHo6Su8RQB9t2QLjNaD4w+02H9qRx+aS7N,iv:cw7IpyaGARcyFXJD/PxZdzDKEknb67RuvWsFaMQkfBo=,tag:gzespFhvUsKmgGxe7aCFUw==,type:str]
        google:
            clientId: ENC[AES256_GCM,data:kACIfFvO+9tXyh1qjX7YD6n5Fg7BjrDrUMJUBcrnvsr8USYrXXErgox+cE3NJIbEwGNC3derI7hit/Tkw3fyZvqOPRVbXoFF,iv:+RaMRqSmRTPqlHMmJ5VG4VhsGxyJp4qPyh5w6ObA9EU=,tag:8hRN4FG9uJC3tv9kfnS+5g==,type:str]
            clientSecret: ENC[AES256_GCM,data:yPCxbWXFkmPGVRxz76vnmmLFaemS1ZJY,iv:9hYPbwu1dzfysQvs7glBInwq//JHy7UKVREYHoVUzbI=,tag:Gu0Gdqxt3A2/U8w/4XZONQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:31Z'
        enc: CiQAFDQ5yiSdCQCjCd38Lxwuuc0iAS3qKcCZoay6G1KbOFvZmIgSSQBtF0FuuRP9WoLRcIMZ0JVUBLlBZ/6TfV7E62clUjcFJGKID9OCXt5esMp1kbzUtVaW+U9UVyp6OlBxT08lioDbsKapq8oXZhs=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-16T07:27:36Z'
    mac: ENC[AES256_GCM,data:/0ECZ4FS41BcO6LeY+IGAFELZaqDRfZExFVEONleIxgRqCq3ufRO1jr3Q5tioTTVywXx1Ncjr9rR8LsvPFp6LicTPDMnapOc7M86we9Xpig/DO+ChoXoyrUuYSjhz8TGTkpJGW/V+wgDmVgrx64VsGQfMLjRBhVn2uEDUTyjt44=,iv:YORM/cwKzOg3bNCzYNI//gPXRh+fW2wlFGNy2hqUwh8=,tag:GwTKNCzNY86myiHsMDB0DA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
