jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:QwGNkSMSBxz/DmfJyXoDALyFsbcVDzMzXPv84FO8DbEJAJAiXvrkv1sslhV4hN7WycaZCjSjyfdi2TaOtUCvIQ==,iv:fz2pgwsTZ0PH+D+CaxwdQp9CgKpdSEVT8ToB4zIBprU=,tag:66h4sj50IcyGzlBBH8PLCQ==,type:str]
    auth:
        state:
            cryptoKey: ENC[AES256_GCM,data:L6tuxJZlgsyVGvGfqfXWzQWANKgnqDcXQRYoU6HiHE8XTq2znzkhcMt/OAQoyHnMe83vd7L3R6aldp6iBTWFVQ==,iv:rF7S7XgUAchGmsRLerhHJPuSYTrg+e7KG6+FedIlj30=,tag:ZXqQWYoBUvLlIwcWwy85gQ==,type:str]
        github:
            clientId: ENC[AES256_GCM,data:w3ThR4W99ccuPG5/rHpeyk+QKgk=,iv:h8uQO5yGNnaX9uBMQHxD3ONv5veMTbre0hbKr8ktH9s=,tag:NzNLf3gQJbe0FDJm+Q/hbg==,type:str]
            clientSecret: ENC[AES256_GCM,data:I5fgRLK+zCq1udFm8i8KdiNe+1YaUXeWaHEYhl+7kow8EwrDsR8kmw==,iv:FLfslGYIYTwceEkQMEUZ80P2kGDNcCASwLXvPymCesA=,tag:a5pGwi6ELZjE0VPEprFa3A==,type:str]
            callbackUrl: ENC[AES256_GCM,data:83tgURBaPZLay/CblValhKKNrarZyDjbpEX8a2Mv2KrCctlR3aQ9BCunUjf2o29GCw/+id48K2w=,iv:EmYZi4u9aTpd0p0/zbfmjmHeFXkkawqEpyiXvCM+pO4=,tag:knPsXjOaMf4W/zJgcpaG0w==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:31Z'
        enc: CiQAFDQ5yiSdCQCjCd38Lxwuuc0iAS3qKcCZoay6G1KbOFvZmIgSSQBtF0FuuRP9WoLRcIMZ0JVUBLlBZ/6TfV7E62clUjcFJGKID9OCXt5esMp1kbzUtVaW+U9UVyp6OlBxT08lioDbsKapq8oXZhs=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-23T13:11:19Z'
    mac: ENC[AES256_GCM,data:vpH8pGkpcPMJg6pjf4MjVNEF4ru9QwslqhqXtnir9j/7TEs1TjxgrCTzp/RtL8uQyhOvRVVzFVlHXGFZP9AJK1PGij7Ff39E6NA9AjGj9q++cDyt538VY15jU55xurO0zO069m+clfD3nI69d3U3l5sqg1KxAKp8A8PCeSnUbfE=,iv:NEBeqDEEQjdp6N5z1NkYRB8YjCKLYZ6lG27mOlbDDuk=,tag:zmtlCsZ/rlLuBkRv5UOqIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
