dependencies:
 - name: prometheus
   version: 11.15.0
   repository: https://prometheus-community.github.io/helm-charts
 - name: grafana
   version: 5.6.4
   repository: https://grafana.github.io/helm-charts
