cluster-autoscaler-chart:
  rbac:
    create: true

  cloudProvider: aws
  awsRegion: us-east-2

  autoDiscovery:
    # Match this with name in aws/eksctl-config.yaml
    clusterName: pangeo-2i2c-cluster
    enabled: true

prometheus:
  networkPolicy:
    enabled: true
  alertmanager:
    enabled: false
  nodeExporter:
    tolerations:
      - effect: NoSchedule
        # Deploy onto user nodes
        key: hub.jupyter.org_dedicated
        value: user
    updateStrategy:
      type: RollingUpdate
  pushgateway:
    enabled: false
  rbac:
    create: true
  server:
    resources:
      # Without this, prometheus can easily starve users
      requests:
        cpu: 0.2
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi
    labels:
      # For HTTP access to the hub, to scrape metrics
      hub.jupyter.org/network-access-hub: 'true'
    persistentVolume:
      size: 100Gi
    retention: 180d
    strategy:
      # Can't really do rolling update, we have a persistent disk attached
      type: Recreate
    service:
      type: ClusterIP

grafana:
  persistence:
    storageClassName: default
  deploymentStrategy:
    type: Recreate

  persistence:
    enabled: true
  service:
    type: LoadBalancer

  grafana.ini:
    server:
      root_url: http://grafana.utoronto.2i2c.cloud/
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: http://support-prometheus-server
          access: proxy
          isDefault: true
          editable: false
