jupyterhub:
  auth:
    type: github
  proxy:
    https:
      enabled: true
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
  singleuser:
    workingDir: /home/jovyan
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "homes/{username}"
    memory:
      guarantee: 512M
      limit: 2G
