# Environment we need *on top* of base PANGEO stack
# Get list of pangeo packages from https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/packages.txt
# BUT REMEMBER TO PICK THE HASH THAT CORRESPONDS TO OUR BASE IMAGE
channels:
  - conda-forge

dependencies:
  - cdsapi
  - cmip6_preprocessing
  - iris
  - pvlib-python
  - seaborn
  - seawater
  - siphon
  - pytables
  - xesmf

  - pip

  - pip:
    # Infrastructure things
    - voila==0.1.23
    - nbresuse==0.3.6
    - nbinteract==0.2.5
    - jupytext==1.6.*
    - RISE==5.6.1
    - jupyter_contrib_nbextensions==0.5.1
    - jupyter-desktop-server==0.1.3
    - jupyter-rsession-proxy==1.2
    - jupyter-tree-download==1.0.1

    # Science things. Prefer conda for these if possible
    - git+https://github.com/trondkr/xESMF.git@27952e1ab2f1b7b23c443953b9d1e079376efb08
    - salem==0.3.0
