jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:zfC2tJUH75wRZBbMPrB280DkV/L82qRvWZ9ne5R0yaEaXnbwCEibUwv8/vVlgBQsgSdFDcLWO6uDtrPXYDfNmA==,iv:JfCmEhrhWQsPgA9TrvpUtdTaIjEVCdsd+G2hYfGbaGY=,tag:JqAoyuF+874sac6IjfisPQ==,type:str]
    auth:
        azuread:
            clientId: ENC[AES256_GCM,data:OMGLIEZJVmdBsIFpgQoQejLs7jOLiFsBnxv+pR4Gn8J5XDrV,iv:Rqm4s6IA0NFriqg7wBrXw1IvpO4TUzmAoepZUXuqSXc=,tag:4AaUBhmYfurYQ556SL6Lpw==,type:str]
            clientSecret: ENC[AES256_GCM,data:r5dKljKN1x8rl3rpHggq4fM3b08O56DJomJSwD/a6mX1GA==,iv:F3jIKyWhn+doJ7g5QycH7PeKBNqQKEcEWLCUrDw/MhU=,tag:/0Cd3q3/nDR070Z+Tz2Iuw==,type:str]
            tenantId: ENC[AES256_GCM,data:rGKQoNUGLgjpJYxT/N3h9mV2KL8phII2V1StXiaNqloAjtl7,iv:yYNafUuyKqSAxVqA4+nFsTpzr9j1EHguwaGWU65nwOw=,tag:JsU9pu3pr/sK/5QqAzVV9g==,type:str]
            callbackUrl: ENC[AES256_GCM,data:6qYUit/G/V52RimPWslcJgzThSkk58f9oD3KJswiHuylI3hS6kn7WWXZlo3kWQ==,iv:dHWcrvTmNHNjsDMk0r+1Res2MXAprHO1Rq9qPJHSp3w=,tag:pmfi/x7Ce9cJVZ6Ht7DenA==,type:str]
        google:
            clientId: ENC[AES256_GCM,data:Rp5N763lfv6R7Y3tTlAHXfPLw8ZOxKSJGMEl9wu+N596d2lsP1SB4rHwE29WBSJmGODj7BVohhSeNWpTwTnJfUuwuPDvRaBj,iv:7hFSVnwf0FvoRTXABOLYXbBcKP+EYD/qwndPidCdeTI=,tag:BpEBwke7refOfqsMkucFUQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:4bxvtVHsVyvzRywrzjrOTCWFQLV+BInj,iv:TQBwDR3/E0vJsIustu9R3fxuBfD08GylWDRjq2OW8lg=,tag:E7fLJ8Q0forbM97KD1N5Og==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-08-28T14:17:10Z'
    mac: ENC[AES256_GCM,data:MXVa1tZ2Vq9WYAJqtvTSmD929pMaD59kOGFZWESvHkDkXs3/BkgGzTniXS14/v9TzO+7Q7mD01Fz9eipVzh6eVtBgzzcf4u+JKIayeNSO+MKRjTO6QJoosSJb8+r4ovMnNE8Eb1gbiFkmb/j0a/5BKAcujLIrKTVzrO6qZCBxQ8=,iv:2hmX0jl6qBFW56BZaCou2JmFyfYjjBKW0bFrXhTNm+k=,tag:ywxOiVJbhqyRtqC4s5MDDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
