jupyterhub:
    hub:
        imagePullSecret:
            username: ENC[AES256_GCM,data:GCNIv9nGo/MUMW9bGTdqHK2vOQ732+1adB6BLkA=,iv:xsfCA41Q1x/yPNj52SoGJCEiNOQ2FpRFElXbpxgznNo=,tag:lDa+/eEHZZ1jX2Mq9K5zfw==,type:str]
            password: ENC[AES256_GCM,data:ZnMYsoTjfAO6snn8arN9CR34C9m67nByGJdwVcnkRzU=,iv:4Lo9p8dK41qSI5YuNt1+xAAypaxqVE65ClB7H1NwG6I=,tag:N+d5kPOU+HCroaD/m0xDHA==,type:str]
    singleuser:
        imagePullSecret:
            username: ENC[AES256_GCM,data:bby5p8UVCPrPDVwr5h4EZWXMj82m/+9bAbZA9XA=,iv:1nu2QuVvsEMzHURS3Qa9XhZfbKh+IhfoB9ODlhpq8fY=,tag:YKkv7hMwp9maxH0D6BLucQ==,type:str]
            password: ENC[AES256_GCM,data:wLswlj2wt/O9GwvD+qlWkVNpHEFRLXfuMVjp/GJ7wpM=,iv:RtyeF3I3gzT5Mt6JH1liDkV+/n+Xi6iU/7kAUKOwcnA=,tag:GGhELltvafqWDyWCEuRcVg==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:zfC2tJUH75wRZBbMPrB280DkV/L82qRvWZ9ne5R0yaEaXnbwCEibUwv8/vVlgBQsgSdFDcLWO6uDtrPXYDfNmA==,iv:JfCmEhrhWQsPgA9TrvpUtdTaIjEVCdsd+G2hYfGbaGY=,tag:JqAoyuF+874sac6IjfisPQ==,type:str]
    auth:
        state:
            cryptoKey: ENC[AES256_GCM,data:u2Hog7+i5joM+gxMxmYO7rx/P+AzC/AJR2djg/VdyvK7LL3F7rOOUR0GgrpjVSFPvQ47MyZGtJ/7kHMnCoPaYw==,iv:6F/9x9b765wSLYhxZqTMRbznNXZeKuLRDzO5n0pzQiE=,tag:8XjmIZeiv7JracpIwp3ArQ==,type:str]
        cilogon:
            clientId: ENC[AES256_GCM,data:6Vfm5mIAIqK0mVcuE5Tir+gLxAa7MxkrwcavtvG3trEYTm3pulWdbhHU37kU44mnE64=,iv:3wEPvSVvrbZ76vja8RqAAlzpsEHE6rHGVWd4xxOhblM=,tag:1JenMz0PZ26pEzijNpHTjg==,type:str]
            clientSecret: ENC[AES256_GCM,data:KSttzLGPAssRwMS/iC+Or+42LIxaKOpWsUDPhySn3tXgZpgntOiyuivjM/cFZO3KfMjdAccBccVAeZFwNKUkymPagk4xcsN7khNw1yNSESOx7Pi08FE=,iv:Dc40viE4RnzivDe6Lz+7B42iZXWnjEKHICDVIm4eoXM=,tag:7aU461Iun8svrYpc5ZTTTQ==,type:str]
        azuread:
            clientId: ENC[AES256_GCM,data:OMGLIEZJVmdBsIFpgQoQejLs7jOLiFsBnxv+pR4Gn8J5XDrV,iv:Rqm4s6IA0NFriqg7wBrXw1IvpO4TUzmAoepZUXuqSXc=,tag:4AaUBhmYfurYQ556SL6Lpw==,type:str]
            clientSecret: ENC[AES256_GCM,data:r5dKljKN1x8rl3rpHggq4fM3b08O56DJomJSwD/a6mX1GA==,iv:F3jIKyWhn+doJ7g5QycH7PeKBNqQKEcEWLCUrDw/MhU=,tag:/0Cd3q3/nDR070Z+Tz2Iuw==,type:str]
            tenantId: ENC[AES256_GCM,data:rGKQoNUGLgjpJYxT/N3h9mV2KL8phII2V1StXiaNqloAjtl7,iv:yYNafUuyKqSAxVqA4+nFsTpzr9j1EHguwaGWU65nwOw=,tag:JsU9pu3pr/sK/5QqAzVV9g==,type:str]
            callbackUrl: ENC[AES256_GCM,data:AYxBoiQw25ueW3svp5YGxVSiPBMyhK8n6W8uEFS6vW/txpyjuLXYoLHViYV6FQ==,iv:t+mnQ7Km8i3o882lrmMjofn3ha4lkUmJTmh1QKoWtzQ=,tag:cEBMFBEA/SghPgHhV8bpQA==,type:str]
        google:
            clientId: ENC[AES256_GCM,data:Rp5N763lfv6R7Y3tTlAHXfPLw8ZOxKSJGMEl9wu+N596d2lsP1SB4rHwE29WBSJmGODj7BVohhSeNWpTwTnJfUuwuPDvRaBj,iv:7hFSVnwf0FvoRTXABOLYXbBcKP+EYD/qwndPidCdeTI=,tag:BpEBwke7refOfqsMkucFUQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:4bxvtVHsVyvzRywrzjrOTCWFQLV+BInj,iv:TQBwDR3/E0vJsIustu9R3fxuBfD08GylWDRjq2OW8lg=,tag:E7fLJ8Q0forbM97KD1N5Og==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-22T06:30:51Z'
    mac: ENC[AES256_GCM,data:jKrp3IdmNd1Aavu8K16szHL9P+7UNgmQ/dzq91R4KA7Nb/oXrpd6IRqn8ZCVMcMhTyoYbdsJtb2WuI1I0+Miu/Gku3IVxL1TN77NpUU0sODb1g2ZRxj2HMuMLxwJ7yZhGgAlEJhzcdAJosQeRK8j8G2llH3b2rjVVIvkRgBIsjs=,iv:Z09Kt4CO1syBa0bLNT8IdgytD+aGxW9sNWIt7L2CQg8=,tag:w7x599CLoI9ePdj3/k8RpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
