jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:SEdp0GP18Jf8/QNgDjaPV53qH4Jm9h8nsvNnmzXl+Qt8/tSk6eEhme11k2wNDXAD5XbisiyXjllGGXpAYNNypw==,iv:XMjirhvs3Z0JxYYxJNybDo/Gz1V855jKnHq1i+t2B8c=,tag:jOam9ZpN4+vAGxJKR3Cqeg==,type:str]
    auth:
        cilogon:
            clientId: ENC[AES256_GCM,data:h57VJ6F2DI1lkXzhyqeEBLFdZ29oh9JOtcrSuz4UJOV/D5POqq9j+7Yx0Iagh8FHgE8=,iv:TS+WI2Xtu11lbV/ZB7CWMuRkadJ8s6nfcWJck+tIvEs=,tag:90YqJxCf1i++zcShiabgsQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:PldaZx94kWAcH1N9j6Kh0wHbQ+LGiO4QdIjGIlzkGu4+8UAPuqzo3suGToYz1hdWQsuMb6X/IkFMFbWsr4wJM/CYO62JfeYgNEKpfUAnlhgPTW9kwpE=,iv:/ZaUrNTNqFlRhZ89tbtLel09vTKAK23XQPE5rj6NtUY=,tag:izD+AE0lRmr9ThfWypYUDA==,type:str]
        azuread:
            clientId: ENC[AES256_GCM,data:+i3/2/+0GIYpo5g7LdGPasKVjSNbey+cSDOPAx2DZeLfk6ug,iv:IOwaxDHMLEli2I9CTH+bd3l1uLYNa4Ya008Tz+AsdeM=,tag:Nr+iTl/0jfZSSjbsFwb0Aw==,type:str]
            clientSecret: ENC[AES256_GCM,data:18enNQdDMwgZ0sYmiJXVUzMEt6O3+6aZ/TiVmLdinSdeww==,iv:IAOv8td7eAO/RRxmAUGYL1xPXY88o1ll5jxzmbD32Gk=,tag:TRzVxAcyeFDEocLHkPoM0A==,type:str]
            tenantId: ENC[AES256_GCM,data:0KI7RrC9BIpUe0XPlhPnW2TG6D4tVSFgnFsKtsWaLhavXhRI,iv:LpfEWEdakSrCKGs9il0DmWQK+Z9SU9cZNH1CmMLTRP0=,tag:UkU+PG8+t8rNOKSZuFutuQ==,type:str]
            callbackUrl: ENC[AES256_GCM,data:HpJZxW8Os4Dt0UJflCDh37IIiAbuIewaEF5WXRPHo6Su8RQB9t2QLjNaD4w+02H9qRx+aS7N,iv:cw7IpyaGARcyFXJD/PxZdzDKEknb67RuvWsFaMQkfBo=,tag:gzespFhvUsKmgGxe7aCFUw==,type:str]
        google:
            clientId: ENC[AES256_GCM,data:kACIfFvO+9tXyh1qjX7YD6n5Fg7BjrDrUMJUBcrnvsr8USYrXXErgox+cE3NJIbEwGNC3derI7hit/Tkw3fyZvqOPRVbXoFF,iv:+RaMRqSmRTPqlHMmJ5VG4VhsGxyJp4qPyh5w6ObA9EU=,tag:8hRN4FG9uJC3tv9kfnS+5g==,type:str]
            clientSecret: ENC[AES256_GCM,data:yPCxbWXFkmPGVRxz76vnmmLFaemS1ZJY,iv:9hYPbwu1dzfysQvs7glBInwq//JHy7UKVREYHoVUzbI=,tag:Gu0Gdqxt3A2/U8w/4XZONQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:31Z'
        enc: CiQAFDQ5yiSdCQCjCd38Lxwuuc0iAS3qKcCZoay6G1KbOFvZmIgSSQBtF0FuuRP9WoLRcIMZ0JVUBLlBZ/6TfV7E62clUjcFJGKID9OCXt5esMp1kbzUtVaW+U9UVyp6OlBxT08lioDbsKapq8oXZhs=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-04T07:13:26Z'
    mac: ENC[AES256_GCM,data:9lWuKDqnwDGVGX5Zqn1TSwFQTqR9FEtzBvOC/QomdzChuiNWurKhl1adgePnIpeS5f4GDDRj3wvtzI2B9tYJRnm0YB+8+i0i1sNmDV52KryIsff2uF6GI/O1Ho2Nn3YoeknGgslNpCp3SIQDadmgg64UuL1EHOUmrhyI6GNIAIM=,iv:FBDUrsSuRTc5qvsRLXuGSA4RzWWUF8SD5DC82MvSdy8=,tag:nf3wFzB877D8kVqf6h/qDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
