channels:
  - conda-forge

dependencies:
  # language runtimes
  - python=3.8.*
  - nodejs=14.8.*

  - beautifulsoup4
  - boto3
  - botocore
  - bottleneck
  - cartopy
  - cdsapi
  - cmip6_preprocessing
  - esmf
  - ffmpeg
  - fsspec
  - gcsfs
  - h5py
  - iris
  - lxml
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  # - opendrift
  - pandas
  - pvlib-python
  - s3fs
  - satpy
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - siphon
  - pytables
  - xarray
  - xesmf
  - zarr
  # Let's make sure that dask-versions match between here & dask gateway
  - dask==2.27.0
  - distributed==2.27.0
  - dask-gateway==0.8.0
  - dask-kubernetes==0.10.1

  - pip

  - pip:
    # Infrastructure things
    - jupyterlab==2.*
    - voila==0.1.23
    - nbgitpuller==0.9.*
    - nbresuse==0.3.6
    - nbinteract==0.2.5
    - jupytext==1.6.*
    - RISE==5.6.1
    - jupyter_contrib_nbextensions==0.5.1
    - jupyter-desktop-server==0.1.3
    - notebook==6.1.4
    - jupyterhub==1.1.0
    - jupyter-server-proxy==1.5.0
    - jupyter-tree-download==1.0.1
    - ipywidgets==7.5.1
    - dask-labextension==3.0.0

    - git+https://github.com/trondkr/xESMF.git@27952e1ab2f1b7b23c443953b9d1e079376efb08
