nfsPVC:
  enabled: true
  nfs:
    serverIP: fs-7b129903.efs.us-east-2.amazonaws.com
    shareName: ""

daskhub:
  jupyterhub:
    auth:
      type: github
      dummy:
        password: watwatwat
    proxy:
      https:
        enabled: true
        letsencrypt:
          contactEmail: yuvipanda@gmail.com
    singleuser:
      profileList:
        - display_name: "Default: m4.xlarge"
          description: "~4CPUs & ~15GB RAM"
          kubespawner_override:
            mem_guarantee: 14G
            cpu_guarantee: 3
            node_selector:
              jupyterhub-pool-name: user-pool-m4-xlarge
        - display_name: "Default: m4.2xlarge"
          description: "~8CPUs & ~31GB RAM"
          kubespawner_override:
            mem_guarantee: 30G
            cpu_guarantee: 7
            node_selector:
              jupyterhub-pool-name: user-pool-m4-2xlarge
      workingDir: /home/jovyan
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: home
            mountPath: /home/jovyan
            subPath: "homes/farallon/{username}"
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "homes/farallon/{username}"
