jupyterhub-ssh:
  hubUrl: https://farallon.2i2c.cloud
  ssh:
    service:
      type: ClusterIP
  sftp:
    enabled: False
daskhub:
  jupyterhub:
    hub:
      db:
        pvc:
          # This gonna store logs
          storage: 10Gi
    proxy:
      https:
        hosts:
        - farallon.2i2c.cloud
