jupyterhub-ssh:
  hubUrl: https://staging.farallon.2i2c.cloud
  ssh:
    service:
      type: ClusterIP
  sftp:
    enabled: False
daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.farallon.2i2c.cloud
