# Things we have learnt so far
# 1. Don't use anything other than -, _, alphanum (and maybe .) in node labels / taints
# 2. EKS' CNI sucks for our use case. https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
#    has number of pods supported per node, and on large instances that's as low as 28.
#    SIGH. Remember this when making nodes
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # Match this with clusterName support/values.yaml
  name: pangeo-2i2c-cluster
  region: us-east-2

nodeGroups:
  - name: core-pool-2020-09-30
    # m5.large gives us only 28 pods, is too small :'(
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 80
    labels:
      jupyterhub-pool-name: core-pool
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jupyterhub-pool-name: core-pool
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
  - name: user-pool-m5-xlarge-2020-09-30
    instanceType: m5.xlarge
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    volumeSize: 150
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jupyterhub-pool-name: user-pool-m5-xlarge
    labels:
      jupyterhub-pool-name: user-pool-m5-xlarge
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: user-pool-m5-2xlarge-2020-09-30
    instanceType: m5.2xlarge
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    volumeSize: 150
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jupyterhub-pool-name: user-pool-m5-2xlarge
    labels:
      jupyterhub-pool-name: user-pool-m5-2xlarge
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: dask-worker-pool-m5-2xlarge-2020-09-30
    instancesDistribution:
      instanceTypes:
        - m5.2xlarge
      onDemandBaseCapacity: 0
      spotInstancePools: 2
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    volumeSize: 150
    tags:
      k8s.io/cluster-autoscaler/node-template/label/dask-pool-name: worker-2xlarge
    labels:
      dask-pool-name: worker-2xlarge
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
