apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # Match this with clusterName support/values.yaml
  name: pangeo-2i2c-cluster
  region: us-east-2

nodeGroups:
  - name: core-pool-2020-09-23
    instanceType: m5.large
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 80
    labels:
      jupyterhub-pool-name: core-pool
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jupyterhub-pool-name: core-pool
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
  - name: user-pool-m4-xlarge-2020-09-23-1
    instanceType: m4.xlarge
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    volumeSize: 150
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jupyterhub-pool-name: user-pool-m4-xlarge
    labels:
      jupyterhub-pool-name: user-pool-m4-xlarge
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: user-pool-m4-2xlarge-2020-09-23-1
    instanceType: m4.2xlarge
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    volumeSize: 150
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jupyterhub-pool-name: user-pool-m4-2xlarge
    labels:
      jupyterhub-pool-name: user-pool-m4-2xlarge
    availabilityZones:
      - us-east-2a
    ssh:
      allow: true
      publicKeyPath: secrets/ssh-key.pub
    iam:
      withAddonPolicies:
        autoScaler: true
