jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:LK/SxN6F1RiL5sqh2Xag+U+zp4pmt1mSWPb5IVjJOWZcdwUFCQTHt+vchGAhf9rAhOr2nNmgSjPA9AraLnVbnA==,iv:VNrOd1bcfc3R1DNNlAgO2gU8inGWZpY7U6O+qP7cHc8=,tag:meCzHqOj73N3XZ5efgbwsA==,type:str]
    auth:
        state:
            cryptoKey: ENC[AES256_GCM,data:V91acAIQ8hkCloBgbxfE+NCZwTyiF1APsUhjqle6DeS/XnnA//HeFYzDMRPUfLJFm9ItV0Oyzi/iMa1jnA+kNA==,iv:HMuYHXGEfjwG/Jv5u7MD/ykCKlKLuzOPijwAtHeaTEs=,tag:njDDX2yAWNe98Dcc5Gf+mw==,type:str]
        github:
            clientId: ENC[AES256_GCM,data:GVlGKQkaC3LuzKF8OHlR5cV0HY4=,iv:MDRkaOw/Z5m7Hbx0ZVgiEevWYu54gotY9PENdh8nrBU=,tag:FhvFw/VDGGTUr9Az4zKk8Q==,type:str]
            clientSecret: ENC[AES256_GCM,data:+AHhc6LAA38FrdVpt7PcV2rKiGIRij89HFY849SaSA6OiPY/5tmK6Q==,iv:Bmw5WmkJ61Ky4N60mnhaLwvQNKPziArnJNbSQ7Glduw=,tag:lLlgUpmnaM/4HD3l1Lojzw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-23T13:10:54Z'
    mac: ENC[AES256_GCM,data:Al4L/P/FhqtrRT/UmnETwM/L2TD5/i1ZRseIiajPVGFopJnLLBgpYx+pLCqt9DftXSfdNETpVrRr51kekD7ICscgnENqmLF/XfLybBIdjwJQ1+2kalk3keO+spfqvfrkjlcfW+DcFfSjEgFl0SUQw1COWXGzkPE/B45zq4+k7mI=,iv:xGD1PaOOGTyko/vhg4p+rb9nj2nPoIq0f/f6g6tFtZk=,tag:DuzoCSduY0NqzIozCDfQZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
