daskhub:
    dask-gateway:
        gateway:
            auth:
                jupyterhub:
                    apiToken: ENC[AES256_GCM,data:QbJhW/g5zqdnTpDIsoFlJnjiCXHInsBIIDbH9w176n/+TDf1s8h2YcdYILsG7mtmsjacjLCHTFFNvX3InYn0ow==,iv:wP9G+Db6CG2FfInr35fzfmJR6fv9NDLH2KqD9MWYy3o=,tag:HwGSLF2CerQmB731XSO/uA==,type:str]
    jupyterhub:
        hub:
            services:
                dask-gateway:
                    apiToken: ENC[AES256_GCM,data:9QL9yDgIBsgD1mLfQSfZaYZ4qE9I30qEOwx7ObGJ6gz81BZqPyDDAqvA8ijYJUOw5r9u0aSx+LUso+nrhbmMoA==,iv:5ggAMmmQl7vYT7+htcaYvbcOb1fNl9A97QmSt4t3nsM=,tag:BtMZc+W/ihGprinmVMKvpg==,type:str]
        proxy:
            secretToken: ENC[AES256_GCM,data:tNq+aJxCvg2y5wW7LOTss0DLm/MDDB02hQDUkD3xL9RrcMObH4cWBHKnWcGLltfwvH0wcjZmjNBNOvzdRNyEjA==,iv:rxkogdsFRG6qETus2N3kieZKqjeyxiJuHPr5geNKyog=,tag:6LUMUBl8IUUsQLljU6SoYg==,type:str]
        auth:
            state:
                cryptoKey: ENC[AES256_GCM,data:1WsdVD5de4s70O5WZ6/UMGkYHZ/8Jzid0RMH1iDceAumOViRxuPGtnwGbL+cfSLzLdNwxdYTM9lxqQlg5DgQhg==,iv:BGH9T77pXdkk41ZeQO83vMm+bn/cPHO5TULLNzMXdRI=,tag:hwdYmeTpC40/66rn+Qr1kg==,type:str]
            github:
                clientId: ENC[AES256_GCM,data:dZJi4Croo/5su2JyAv4DXckJD7I=,iv:a/5NBPe6bvAUJRH1wGSOBuX3VvIccp7hVT8y87HhqM0=,tag:1Y0QW8fOQXEG4HBXPKxgEA==,type:str]
                clientSecret: ENC[AES256_GCM,data:o/6bRDsVUImSOG60mRrIQEsh8RvaWFZvqDFlX5M3XYP2mJjgOvra5A==,iv:pFpc0ixnGX8onFV1xCIoVE2KZ3dmq1XEVU5BjtG4Hrw=,tag:UUywhl/QM1+K7Ne5S1+qfA==,type:str]
                callbackUrl: ENC[AES256_GCM,data:uK0hP/l+0omy43RLjeUKYUKkZzvfh50fZmZl7JXgOcPF0S9ApZyQxBv9UJFrTB+C,iv:PmZ1aSLtTi966ij8IV+qmdU2c0DTZgYZZWpDJSpmWZQ=,tag:rUvIXDzeiwQEQfuA9FvVsA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-28T16:10:49Z'
    mac: ENC[AES256_GCM,data:E234gldQSl3o6yvgUQfr/cT/KZkqcQnauGtdORNKvGvXncQc62VNgDrgtCeXdg9Mdeohfyk4tfh/lx0QnSdeuq/cooN6VhdLLI5knNsXg524NleFaCX+7pO3IVqZdvF8g5R93Ixu3qE3F5DOhkwa17tqC0mS8JblzTmERDSwqik=,iv:AJCVBQda2fpBevnnRtBBWYGc76iD4JH9kDvJelrlS4E=,tag:I2Kqo/Oa9K1+EDWnagSVlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
