daskhub:
    dask-gateway:
        gateway:
            auth:
                jupyterhub:
                    apiToken: ENC[AES256_GCM,data:QDQp8+DWGN3gJ+BDD53Ax97R2r3lbHkwYP/fnEsNRZew2q+RSRSo1SKVH7CBa0f99qIINiT8eW6GWAJ18v1A1Q==,iv:wKH3kKUTJM3HSAWfHLjqeNFgEL8YSriv++H6EqQ1vEY=,tag:nh2tLm71xNRda/x4DUrn+A==,type:str]
    jupyterhub:
        hub:
            services:
                dask-gateway:
                    apiToken: ENC[AES256_GCM,data:I7iEmM7QzRYu5fVIJnuaCLgnL0Tw9AHONtuZLXwZIkMLEKPnZ4Shx5rHDQpUsX85fG0RNplmyUsKDQLXfZEceQ==,iv:pKj7pTFDH1c93xc7x3Hc/EQtE5YMPhjR24vJTKkOA3o=,tag:+7XfCFyC7e5MB1wYfNeL3Q==,type:str]
        proxy:
            secretToken: ENC[AES256_GCM,data:NMtRKb/m/fjg7Kaw1C+mYkq6UD1PXRxXd/494YtAUSTqH+fUF2QGSDnzItbj9aPLWGhFzw7vzAx7pXLIXcALgg==,iv:vpqjTLGJ3Ra2JQ3OgBqD0N+Xp0M0nzKug/kh5jr6VCA=,tag:Ei5FGBHB42Rg5xb1azHyrg==,type:str]
        auth:
            state:
                cryptoKey: ENC[AES256_GCM,data:h46tZ3xsTEZWizwupnXPOc/kKZkL2p5WnQOM8+pgB7pTgDyCtCz53euthl8QdlsCp7BhUVQ7qHGPxCa5/FMgIA==,iv:Liy1I2WmVeNMuL/AuCEZrvffM5k5WP46OF2QOlBlJ80=,tag:fSr3Oaqb2wA5k6oSyk344w==,type:str]
            github:
                clientId: ENC[AES256_GCM,data:wClF3VKaPBUJ6zQlKyR3662IsfM=,iv:/Xmjq92Qju6mKE9Ja2mx9WVtE0YpS5B3OmNEjhRw6Qk=,tag:VG4b/Qs8oY8IMZQT4yVIMg==,type:str]
                clientSecret: ENC[AES256_GCM,data:LRr5qBgE7c0NyjzBAMDIVGLia4PgQsOit4ImXIKPzHR3AOPyLGJYUg==,iv:TuLYiGyH8M9UpagShbF7gUgVXMUcsjmiruSvi7nlQCQ=,tag:oDZqHWWnAMme+wgpzYiJdA==,type:str]
                callbackUrl: ENC[AES256_GCM,data:dCrs/JFR6MNWYU8i65MVVUT94o5zWaGUCtde6sSTsCYaDigq8TqLFCPcocRyWgNCcwuWVb/YBlA=,iv:3HtYFrABZKhdnYdKVaqcqNHFlg7PphTYANOdA7BcHZU=,tag:3x3U4H9UWPn5ls5GIvmtHQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:31Z'
        enc: CiQAFDQ5yiSdCQCjCd38Lxwuuc0iAS3qKcCZoay6G1KbOFvZmIgSSQBtF0FuuRP9WoLRcIMZ0JVUBLlBZ/6TfV7E62clUjcFJGKID9OCXt5esMp1kbzUtVaW+U9UVyp6OlBxT08lioDbsKapq8oXZhs=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-28T13:07:41Z'
    mac: ENC[AES256_GCM,data:dMWM8kH8xq+VBXEhN2t0dEiWniO3IGYpzFVvw42Jsm4QfeMI0Hw8xsXwcTFgzhnU7mDPulI+J/M9+EAcugczriiJn3vH64L3bQArl2b/ptCw7OSxepl5DAnUwJP21GVkPQzCxqN4oniLHVFgS0TSu0jxC6EX+sOrQRnxHdIUCpA=,iv:901n2LrXKG8sbdM1ACZz7kNxvmI/muM1eRk5KChPung=,tag:drmcb6OQMHBdpA5hArsNyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
