jupyterhub:
  proxy:
    https:
      enabled: true
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
  singleuser:
    workingDir: /home/jovyan
    storage:
      type: none
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 2G
      limit: 4G
