jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:zfC2tJUH75wRZBbMPrB280DkV/L82qRvWZ9ne5R0yaEaXnbwCEibUwv8/vVlgBQsgSdFDcLWO6uDtrPXYDfNmA==,iv:JfCmEhrhWQsPgA9TrvpUtdTaIjEVCdsd+G2hYfGbaGY=,tag:JqAoyuF+874sac6IjfisPQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    lastmodified: '2020-07-01T13:15:27Z'
    mac: ENC[AES256_GCM,data:G0TKo8dtRlTzfk3JkZMPQv2tbnP+zrkXx/kwXq4EkdnVBmc4gz5fxUypr8GKyCdiBwNzytquljdbvG61Z0XPYSsrBVfxmHa6u24/V+0+LnMYxjl0VMDgjo782+Pp6NzZ5RGLR3gG5X/omeo2HimsNiaa0npl2jRDXCj7wKRRra4=,iv:M9yJk6PXjur2J/kvu/Jl4soeydOJEj2eCLJg0PlukTg=,tag:82rfRYK0Ua8qJiIu4e887A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
