jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:zfC2tJUH75wRZBbMPrB280DkV/L82qRvWZ9ne5R0yaEaXnbwCEibUwv8/vVlgBQsgSdFDcLWO6uDtrPXYDfNmA==,iv:JfCmEhrhWQsPgA9TrvpUtdTaIjEVCdsd+G2hYfGbaGY=,tag:JqAoyuF+874sac6IjfisPQ==,type:str]
    auth:
        google:
            clientId: ENC[AES256_GCM,data:Rp5N763lfv6R7Y3tTlAHXfPLw8ZOxKSJGMEl9wu+N596d2lsP1SB4rHwE29WBSJmGODj7BVohhSeNWpTwTnJfUuwuPDvRaBj,iv:7hFSVnwf0FvoRTXABOLYXbBcKP+EYD/qwndPidCdeTI=,tag:BpEBwke7refOfqsMkucFUQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:4bxvtVHsVyvzRywrzjrOTCWFQLV+BInj,iv:TQBwDR3/E0vJsIustu9R3fxuBfD08GylWDRjq2OW8lg=,tag:E7fLJ8Q0forbM97KD1N5Og==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    lastmodified: '2020-07-07T20:10:50Z'
    mac: ENC[AES256_GCM,data:UyLsFpCdXHUBoJT2An6oVHSnsECAS5B7ETcCl42q3KQfWf2Be8O/cHenDttyh5ez46XLb8d/NUnB/H0H7SRfaZOnU5qOD9jdYaiqMIv21o3sfeES/advcr/+0x2ozXH4C+Ui+YMn7LAIyYlmC7yTrCiIWXCPZwVb1Il14ZLSkVc=,iv:GSrsxsxNqYPKxPXyR8P1EwaOMmdsJTM+IHpk+L4PzdQ=,tag:gyNUOZ4PY9ggi5kHiYWUlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
