jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:SEdp0GP18Jf8/QNgDjaPV53qH4Jm9h8nsvNnmzXl+Qt8/tSk6eEhme11k2wNDXAD5XbisiyXjllGGXpAYNNypw==,iv:XMjirhvs3Z0JxYYxJNybDo/Gz1V855jKnHq1i+t2B8c=,tag:jOam9ZpN4+vAGxJKR3Cqeg==,type:str]
    auth:
        google:
            clientId: ENC[AES256_GCM,data:kACIfFvO+9tXyh1qjX7YD6n5Fg7BjrDrUMJUBcrnvsr8USYrXXErgox+cE3NJIbEwGNC3derI7hit/Tkw3fyZvqOPRVbXoFF,iv:+RaMRqSmRTPqlHMmJ5VG4VhsGxyJp4qPyh5w6ObA9EU=,tag:8hRN4FG9uJC3tv9kfnS+5g==,type:str]
            clientSecret: ENC[AES256_GCM,data:yPCxbWXFkmPGVRxz76vnmmLFaemS1ZJY,iv:9hYPbwu1dzfysQvs7glBInwq//JHy7UKVREYHoVUzbI=,tag:Gu0Gdqxt3A2/U8w/4XZONQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:31Z'
        enc: CiQAFDQ5yiSdCQCjCd38Lxwuuc0iAS3qKcCZoay6G1KbOFvZmIgSSQBtF0FuuRP9WoLRcIMZ0JVUBLlBZ/6TfV7E62clUjcFJGKID9OCXt5esMp1kbzUtVaW+U9UVyp6OlBxT08lioDbsKapq8oXZhs=
    azure_kv: []
    lastmodified: '2020-07-07T20:10:38Z'
    mac: ENC[AES256_GCM,data:wysmsGu1C5QwYrxZaysvU6wWmT3AblQKFzAwrRa5qNbXs/W+itcVtXeTbGoVk4yuqHnfZWfxhhbc+qum8b4KbiJKhIhpdkZODcFL3y+cmzyLrN/1YquiUw1d0olkNTPb3xoiblGDCAVu3g/iFflw+Bqe7YjDkNUQouAb0YBda/w=,iv:fPV4iTi+n3i/isU3o3JgvWmr81edpObAsvLVx840p7w=,tag:TVFPZ2c3BzTq8rNfwJ22aw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
