daskhub:
  jupyterhub-ssh:
    hubUrl: https://ohw.pangeo.2i2c.cloud
  jupyterhub:
    hub:
      db:
        pvc:
          # This gonna store logs
          storage: 10Gi
    proxy:
      https:
        hosts:
        - ohw.pangeo.2i2c.cloud
