daskhub:
    dask-gateway:
        gateway:
            auth:
                jupyterhub:
                    apiToken: ENC[AES256_GCM,data:TvHMFPYK0BUQE43d4HPyp9cKKCoGw30sLJrCDu86pMkiqM7BsozJ9+IEy8s+NhOXvmv8cgZqumME7yLHewPdKA==,iv:9WvhlxLy1rpOFl5oner6/t+SD0G1CKb5m8gHRUjxVfE=,tag:r7n8NEa/egD6Wn1p156Jtg==,type:str]
    jupyterhub:
        hub:
            services:
                dask-gateway:
                    apiToken: ENC[AES256_GCM,data:sREJE+7Cm7psc4MPI2mBe5yaNRQrc9APkY8D78y6Nr9q7BZsHBVdMjGKw9Stk0NM4dvKEaHxXtmvs7YIYB/9yA==,iv:gkT7YZgBZaAOF6yhacprQ+sItSYNZz1gUy0KG50T1bU=,tag:tO9gKzSIv4Jny5AzwsGf2A==,type:str]
        proxy:
            secretToken: ENC[AES256_GCM,data:mGdTmqrSqtdNLKmu0m2RfnnSdQq2xwIpqV2eQooPAI4Xg7FtMXKRUiMqjkXGfIxC8nJbLpmuCVQs33yr9K2YKA==,iv:cZOHrLtVmcdjxlxEx/26Gz+K6sKcv2oVTg74UsEinIk=,tag:yLD2qdA3ttTr0ANh4lfAmw==,type:str]
        auth:
            state:
                cryptoKey: ENC[AES256_GCM,data:EeA7WPvcNFc8i8I+9pFRlQc7mF8CRY8s/mmQaOc98C3G73N9JXchFa6XgYgx1gGvZhoKlZirNHq35Qxpxif21A==,iv:tDQJGjqZJbFtfI/gSDUzy4m0IRdp/CPh/jlwl7DxwNw=,tag:NI2zWZWod2Y2kQ89Y206Cw==,type:str]
            github:
                clientId: ENC[AES256_GCM,data:+K3PPfFpWLiMf7CCtQ4LyNItTMg=,iv:PePAZCPypeP0U3WM1NcsLNQ7g7jmtLOySxLIQwqKW8A=,tag:I7ugMxlaJENeBd1RarRGZw==,type:str]
                clientSecret: ENC[AES256_GCM,data:FEsZiIo4g6vKqwCnghGNZVrcKmhOhlaAGlxHe6PtAWDYZgsJtXjC5g==,iv:OHfJWdTm3tyAovWCy5t8CyvdZ0QD7i4WcFs3GTXSrvo=,tag:821Dwsxyi5gaYRInA0x5RA==,type:str]
                callbackUrl: ENC[AES256_GCM,data:IPlmqqaxoyC9XR/mw4LWWzM+7GxXThWG+ycizrIbPNeIpreYXhM5XYdjI6P7kw==,iv:3r1JgD/lwfyHcKqV/NDPW3Ep4wHZRg9iLB24HfunBzw=,tag:mZmvu/7ghPdzPQHgZDprDA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:26Z'
        enc: CiQAFDQ5ytipTU+81DbslBEtqcsIp3o2cCnkMiIaspkoc7WblykSSQBtF0FugrhokuuFAUCLEsyfdsEwLiOriocMhBUsEbPFqTTApZwA/deiO0PRifmxDNLmeCjs42nHenhHzAa/+1QXKmzQCAcUfmI=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T07:28:22Z'
    mac: ENC[AES256_GCM,data:FiylfmwuVzqMfQvy9kfNhg2utuKCf6QXwDoIbEsgWNCX/gAscVrang5t0MLYznieoQENqoky35f6y1HGRwCs6F6oPI0yoAQMhZszY7IIP5T6qLJtd00eKzxsARb/uApYYCkME4X8sVtpz85OLJhL1naghTM2TSn173gZXzaueDA=,iv:0xMZk5CeQfmLOIX9cUl8rUKe/j7gtG0uEhhwdZZiXR8=,tag:+x/nMDar3O0v3lzF4Q0mRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
