daskhub:
    dask-gateway:
        gateway:
            auth:
                jupyterhub:
                    apiToken: ENC[AES256_GCM,data:W/n2j9qYutOkl+U2Shkq0Ai/DIkN3F+tHc7s/JE4oCzepg8QLoPX8GzvWXxbGQpCA/0wLkSAPPNvUDlKwrPmxw==,iv:DD7mT7ibnqyyHMkjiKkHV9JUp25U6OSEFAuv3Mx2AUc=,tag:J0jkkzEHhoufIV6kb5iqkA==,type:str]
    jupyterhub:
        hub:
            services:
                dask-gateway:
                    apiToken: ENC[AES256_GCM,data://YEExxAQwMRfJeQ6tMgCCD6lK+PfCCm+lORF3onPxvofzyAhMeZGnAyQ1BvSujFUZg1iUUSoS/6pOvjJjTH6Q==,iv:+sui2NUIet1It5Onltpqy3vGaHJzgTD6in9kB1YiTHY=,tag:uEr5fYwY5Lf5W0LpmCvU0g==,type:str]
        proxy:
            secretToken: ENC[AES256_GCM,data:D70Y7rDG8c1X4157dw15u28wWSZ4Fou4p6rBzyljxkAtqPWsEgOiRhdb7KHccmZ1JbF+GSD0UNP0A3upE3afDw==,iv:QRww19A+5342vL6A9TeIDFht3CrxujfwCFnGBN4MGhc=,tag:1LPj8v74doKVO3CQEbTupw==,type:str]
        auth:
            state:
                cryptoKey: ENC[AES256_GCM,data:1IPcspEPakTUicM5r3OftXd4WlfNEI1xKpCWcSMmDPXzeu5oRbMjRqQi6sYX+GIVtL4yv8Ljb5gwQ/A6aWMX7w==,iv:YWphd4XZc9Sy7QRVXKXokASqGL/unItAuireyeooYSo=,tag:DPX9ivLUOXoid6v25kH6zA==,type:str]
            github:
                clientId: ENC[AES256_GCM,data:uYHPf4i0iXGmHzvD7yz+E2pLAMc=,iv:8rl+tBb4VugwImxhcZ7AmgmuE1wmxM2zTX6xfSn8kXE=,tag:/5jAwMie+A6jAhsJwfKZSw==,type:str]
                clientSecret: ENC[AES256_GCM,data:7n8kQnJl/1BLa5OkrzJ4eWDsaV41R9wSOpSDO9vGgecmKGfz4GCpZg==,iv:voT44EKAaUAuZlZKZb+sijPawQLPVwWhV7HgH7J4lPw=,tag:ZSf4oLCoykYvyeqvAI5VlQ==,type:str]
                callbackUrl: ENC[AES256_GCM,data:YQs/mRCfxf0cyQ4Tppgncg0aBx/vxisHpwWEy2uFRxBXlYL+esoTi2j4z1dibULC14fvSAHh,iv:pMWJ2KiYMQ+i8Vi59wMyehYVe91DGcdBgGX+pPzqmk8=,tag:kNk4YOwkNu3cL6/8iMgk+w==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/jupyterhub-deploy
        created_at: '2020-07-01T13:15:31Z'
        enc: CiQAFDQ5yiSdCQCjCd38Lxwuuc0iAS3qKcCZoay6G1KbOFvZmIgSSQBtF0FuuRP9WoLRcIMZ0JVUBLlBZ/6TfV7E62clUjcFJGKID9OCXt5esMp1kbzUtVaW+U9UVyp6OlBxT08lioDbsKapq8oXZhs=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T07:26:39Z'
    mac: ENC[AES256_GCM,data:ttHX34/0APComZNHNXjZHwZHxR8ncMlemiCbviYQYxBkqrobw6jzGoP577PgwMJBO2eTm3M1HwYnoLkSzTrpZ0NMHlcphNExnsH8+jVzdoBzhzlnm6TNJP3JFqzEwCOltCMNX6/FATmKQSIoP2uQYtbWJuXR1CnCEfUJe+sOqH8=,iv:+/yWZSGqYypm/jNdquz+rlBreEV1Bv4czUqh1J07nbg=,tag:mt3ezDoj294TOW1Kl6nq6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
