jupyterhub:
  proxy:
    https:
      enabled: true
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
  singleuser:
    workingDir: /home/jovyan
    storage:
      type: none
    memory:
      guarantee: 128M
      limit: 1G
