etcJupyter:
  # Options for Jupyter Notebook itself, set for each user
  jupyter_notebook_config.json: {}

nfsPVC:
  enabled: false
  # If you want a PVC with NFS that can be used to mount home directories
  # nfs:
    # serverIP: # IP of your NFS Server
    # shareName: # Path of your NFS share export

jupyterhub:
  proxy:
    chp:
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.5
          memory: 256Mi
        limits:
          memory: 256Mi
    traefik:
      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          memory: 512Mi
  singleuser:
    events: false
    cloudMetadata:
      enabled: true
  hub:
    resources:
      requests:
        # FIXME: Set up
        cpu: 2
        memory: 2Gi
      limits:
        memory: 2Gi
    extraConfig:
      01-working-dir: |
        # Make sure working directory is ${HOME}
        # hubploy has a bug where it unconditionally puts workingdir to be /srv/repo
        c.KubeSpawner.working_dir = '/home/jovyan'
  scheduling:
    userScheduler:
      enabled: true
      resources:
        requests:
          # FIXME: Just unset this?
          cpu: 0.01
          memory: 1Mi
        limits:
          memory: 512Mi