etcJupyter:
  # Options for Jupyter Notebook itself, set for each user
  jupyter_notebook_config.json: {}

nfsPVC:
  enabled: false
  # If you want a PVC with NFS that can be used to mount home directories
  # nfs:
    # serverIP: # IP of your NFS Server
    # shareName: # Path of your NFS share export

jupyterhub:
  proxy:
    chp:
      resources:
        requests:
          cpu: 0.5
          memory: 256Mi
        limits:
          memory: 256Mi
    traefik:
      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          memory: 512Mi
  singleuser:
    events: false
    cloudMetadata:
      enabled: true
  hub:
    concurrentSpawnLimit: 200
    readinessProbe:
      enabled: false

    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        memory: 2Gi
    extraConfig:
      01-working-dir: |
        # Make sure working directory is ${HOME}
        # hubploy has a bug where it unconditionally puts workingdir to be /srv/repo
        c.KubeSpawner.working_dir = '/home/jovyan'
      02-prometheus: |
        # Allow unauthenticated prometheus requests
        # Otherwise our prometheus server can't get to these
        c.JupyterHub.authenticate_prometheus = False
      03-no-setuid: |
        # Disable 'sudo' & similar binaries, regardless of image contents
        c.KubeSpawner.extra_container_config = {
          'securityContext': {
            # Explicitly disallow setuid binaries from working inside the container
            'allowPrivilegeEscalation': False
          }
        }
  scheduling:
    userScheduler:
      enabled: true
      resources:
        requests:
          cpu: 0.1
          memory: 512Mi
        limits:
          memory: 512Mi