name: Deploy
on:
  push:
    branches:
    - staging
    - prod

jobs:
  build:
    name:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://yuvipanda/hubploy:202007030947410a596a
        name: unlock git-crypt secrets
        env:
          SOPS_GCP_DECRYPT_KEY: ${{ secrets.SOPS_GCP_DECRYPT_KEY }}
        with:
          entrypoint: /bin/bash
          # Google Application Default Credentials are used to authenticate sops
          # to GCP KMS for decrypting our secrets. We'll set the appropriate env
          # var (GOOGLE_APPLICATION_CREDENTIALS) to point to this service account
          # json file. See https://cloud.google.com/docs/authentication/production
          # for more info.
          # We explicitly pass this env var only to steps that need it, so we
          # don't accidentally authenticate in places we don't need to.
          args: -c "echo ${SOPS_GCP_DECRYPT_KEY} >  ${HOME}/sops-key.json"
      - uses: docker://yuvipanda/hubploy:202007030947410a596a
        name: build & push image if needed
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/sops-key.json"
        with:
          args: build demohub --check-registry --push
      - uses: docker://yuvipanda/hubploy:202007030947410a596a
        name: Setup Helm
        with:
          entrypoint: /bin/bash
          args: -c "helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ && helm repo update"
      - uses: docker://yuvipanda/hubploy:202007030947410a596a
        name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/sops-key.json"
        with:
          args: deploy demohub hub staging
      - uses: docker://yuvipanda/hubploy:202007030947410a596a
        name: Deploy to prod
        if: github.ref == 'refs/heads/prod'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/sops-key.json"
        with:
          args: deploy demohub hub prod
